version: '3.8'

services:
  redis-server:
    image: redis:7-alpine
    command: redis-server --requirepass $$(cat /run/secrets/redis_password)
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    secrets:
      - redis_password
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"  # RTSP
      - "1935:1935"  # RTMP 
      - "8888:8888"  # HLS/WebRTC
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./certs:/certs
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8888/"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1'
    restart: unless-stopped

  vision-app:
    build: 
      context: .
    runtime: nvidia
    environment:
      - RTSP_URL=rtsp://admin:Password01@192.168.1.64:554/Streaming/Channels/1/?transportmode=unicast
      - REDIS_HOST=redis-server
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./config:/app/config
      - ./certs:/app/certs
    depends_on:
      redis-server:
        condition: service_healthy
      mediamtx:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4.0'
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jetsonnano/redis_data
      o: bind

secrets:
  redis_password:
    file: ./secrets/redis_password.txt
